### ISSUE TITLE
HDR-Controller will not install

### ISSUE THREAD

**Issue by chesley96** [IDimitrovDev/HDR-Controller#1]
Installed certificate exactly as explained in the readme, but app will not install.
Here is the message received:  
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

**Comment by chesley96** [comment]
Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎12/‎2022
OS build	22623.746
Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by IDimitrovDev** [comment]
Thank you for reporting the issue. It was related to expired certificated and new release with the app repackaged has been published
